// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencies

import (
	"payment-airpay/application/services"
	"payment-airpay/infrastructure/gateway/acleda"
	"payment-airpay/infrastructure/publishers"
	"payment-airpay/infrastructure/service"
)

// Injectors from wire.go:

func WireCreatePaymentService() *services.CreatePaymentService {
	acledaGateway := ProvideAcledaGateway()
	PaymentAcleda := ProvideTransactionService()
	createPaymentService := services.NewCreatePaymentService(acledaGateway, PaymentAcleda)
	return createPaymentService
}

func WireAcledaGateway() *acleda.AcledaGateway {
	acledaGateway := ProvideAcledaGateway()
	return acledaGateway
}

func WireTransactionService() *service.PaymentAcleda {
	PaymentAcleda := ProvideTransactionService()
	return PaymentAcleda
}

func WirePublisher() *publishers.PublisherLog {
	publisherLog := ProvidePublisher()
	return publisherLog
}
